### ISSUE TITLE
Allow specifying `Hasher` used by `std:collections::HashMap`

### ISSUE THREAD

**Issue by NickHu** [dermesser/memoize#18]
The default `std::collections::HashMap` uses SipHasher, which is quite slow. For higher performance, one might want to use FxHasher, e.g. as provided by the following crate: https://docs.rs/rustc-hash/latest/rustc_hash/.

Currently, there is no way to specify which Hasher to use in memoization.

**Comment by dermesser** [comment]
This is a good idea. I will attempt an implementation in the next couple days, as time permits.

**Comment by Boscop** [comment]
[AHash is even faster](https://github.com/tkaitchuck/aHash/blob/master/compare/readme.md#Speed) and I'd like to use it with memoize.

@NickHu It's also interesting to read the criticisms of FxHash: <https://github.com/tkaitchuck/aHash/blob/master/compare/readme.md#fxhash>

So yeah, it would be great if users of the crate could choose the hasher they want to use :)

Btw, in my own in-memory hashmaps I've switched to hashbrown, it uses AHash by default:
https://github.com/rust-lang/hashbrown#performance (Compare the `hashbrown ns/iter` values across both tables, with AHash it takes about half the time.)
std now uses hashbrown's HashMap but with SIP hasher, which makes it slow:

https://github.com/rust-lang/hashbrown#performance
(Using hashbrown::HashMap or std HashMap with AHash would be almost equivalent.)
If adding hasher configuration API would be out of scope for now, I would be happy if `memoize` just switched to hashbrown::HashMap, because that would be the fastest.
This would allow `memoize` to keep the hashmap & hasher as an implementation detail and they could be replaced if faster ones came along (probably not soon).

**Comment by NickHu** [comment]
I am aware of AHash, however the last time I looked at it it had significant limitations on a platform that isn't x86 with hardware AES instructions (e.g. wasm), which would be my primary use case. It was either a hassle to compile or slower than FxHash at the time, or possibly even something else, I don't remember which.

In either case, I think a generic implementation is the correct thing to do.

**Comment by dermesser** [comment]
Folks, keep in mind -- this crate is supposed to speed up a slow function by 100x through storing its result. At that point, a few nanoseconds on the hash function don't matter that much anymore IMO. It is not the best solution for high performance or general purpose hash tables, in which case one should simply use a hashmap of one's choice directly.

That being said, of course I accept PRs for such features :)

**Comment by blyxyas** [comment]
I'll try to implement this.

**Comment by NickHu** [comment]
Could we please have a new crate release for this? Many thanks for your hard work @blyxyas and @dermesser!

**Comment by blyxyas** [comment]
Only @dermesser can release a new crate version. Also, thanks! :D
